[project]
name = "difftest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zippermerge", email = "zippermerge12@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "zippermerge>=0.1.0",
]

[project.scripts]
difftest = "difftest:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
]
